language: go

sudo: required

services:
  - mysql

before_script:
  - mysql -e "SELECT version();" &>/dev/null
  - mysql -e 'CREATE DATABASE IF NOT EXISTS leetcode_mysql;'

script:
  - bash test.sh $(which mysql) leetcode_mysql